-- MySQL Script generated by MySQL Workbench
-- Sat Jun 25 16:53:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema celebal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema celebal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `celebal` DEFAULT CHARACTER SET utf8 ;
USE `celebal` ;

-- -----------------------------------------------------
-- Table `celebal`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `celebal`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NULL,
  `age` INT NULL,
  `email` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
